//
// Created by maaya on 24/03/2024.
//

#ifndef WINTERRANK_TO_BUBBLE_INFO_H
#define WINTERRANK_TO_BUBBLE_INFO_H


class to_bubble_info{
    //this class is for each team, will contains the following Data for each team:
    //1. the number of players in said team(which will require a new function, get num_of_participants in Value
    // classes, in player it will return 0, in team it will return player_by_strength->num_of_nodes;
    //this class should be generated by the node itself to make it easier for us
private:
    int to_bubble;
    int team_id;
    int num_of_participants;
public:
    bool operator==(const to_bubble_info &rhs) const {
        return to_bubble == rhs.to_bubble;
    }

    bool operator!=(const to_bubble_info &rhs) const {
        return !(rhs == *this);
    }


    int getNumOfParticipants() const {
        return num_of_participants;
    }

    void setNumOfParticipants(int numOfParticipants) {
        num_of_participants = numOfParticipants;
    }

    int getToBubble() const {
        return to_bubble;
    }

    void setToBubble(int toBubble) {
        to_bubble = toBubble;
    }

    bool operator<(const to_bubble_info &rhs) const {
        return to_bubble < rhs.to_bubble;
    }

    bool operator>(const to_bubble_info &rhs) const {
        return rhs < *this;
    }

    bool operator<=(const to_bubble_info &rhs) const {
        return !(rhs < *this);
    }

    bool operator>=(const to_bubble_info &rhs) const {
        return !(*this < rhs);
    }
    void add_change(int change){
        this->to_bubble+= change;
    }
    to_bubble_info(int team_id, int num_of_participants, int to_bubble):team_id(team_id), num_of_participants
            (num_of_participants),to_bubble(to_bubble){}
    to_bubble_info(const to_bubble_info& other):team_id(other.team_id), num_of_participants
            (other.num_of_participants),to_bubble(other.to_bubble){}
    to_bubble_info(int to_bubble):to_bubble(to_bubble){
        team_id = 0;
        num_of_participants = -1;
    }

    ~to_bubble_info()=default;


};


#endif //WINTERRANK_TO_BUBBLE_INFO_H
